### ISSUE TITLE
Maya issue - AttributeError: 'NoneType' object has no attribute 'layout'

### ISSUE THREAD

**Issue by garysb** [huntfx/vfxwindow#2]
Hi Peter,

I am trying to make a cross application plugin to be run on Maya, Blender, 3DSMax, Unreal, Unity3D, and Standalone Python and it seems your package is the perfect fit *(that sounds dirty some how)*. I am currently using Qt.py on top of PySide2 and have a functioning version for the most part.

As a test I have tried incorporating VFXWindow to ease the management required to handle the window management, but I am unable to get it to display a window properly due to the following error in Maya:

```bash
# Error: 'NoneType' object has no attribute 'layout'
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
#   File "C:\Users\gary\Projects\Area28\Area28Module\vendor\area28\ui\__init__.py", line 88, in create
#     ui_window = met(*args, **kwargs)
#   File "C:\Users\gary\Projects\Area28\Area28Module\vendor\area28\ui\about.py", line 54, in __init__
#     self.setCentralWidget(self.container)
#   File "C:\Users\gary\Projects\Area28\Area28Module\vendor\vfxwindow\maya.py", line 548, in setCentralWidget
#     self.parent().layout().takeAt(0)
# AttributeError: 'NoneType' object has no attribute 'layout'
```

And within Blender I get an error due to no QApplication defined.

```bash
QWidget: Must construct a QApplication before a QWidget
```

## Questions

1) Does VFXWindow manage parenting the QMainWindow within the application as it looks like the parent is not defined in Maya (2020.3) and in Blender (2.82) the QApplication is not defined.

2) Should I still pass in the parent window (created by myself in Blender, and returned from omui.MQtUtil.mainWindow() in Maya) and do I still need to wrapInstance() as I noticed you have an implementation of wrapInstance?

3) What would be the best way to approach multiple windows, as an example I have an about, chat, login. For my current solution I have built a ui manager that stores a reference to the window and replaces it each time a new ui is shown.

4) Is there somewhere I can find a slightly more complete example. I have looked at the wiki page and the tests but both seem very minimal?

## Code Snippets

Below is the manager used to create the ui using a string to load the module eg `ui.create('account.LoginUI')`:
```python
def create(interface, *args, **kwargs):
    """Create a window using the provided UI class. A check is made to ensure
    that only one window is open at any point in time.
    """
    log.debug('creating window: {}'.format(interface))
    global ui_window

    # delete the current interface before creating a new one
    delete()

    if ui_window is None:
        p, m = interface.rsplit('.', 1)
        mod = import_module(__name__ + '.' + p)
        met = getattr(mod, m)
        # ui_window = met(parent=get_main_window(), *args, **kwargs)
        ui_window = met(*args, **kwargs)

        log.debug('created window {} ({})'.format(ui_window.objectName(), ui_window.windowType()))

    result = ui_window.show()
```

and below is an example of using the ui to create an about window:

```python
from area28 import PREFIX, PATH
from area28.utils import logger
from vfxwindow import VFXWindow
from PySide2 import QtWidgets, QtSvg, QtGui

# setup the logger for this module
log = logger.getLogger(__name__)


class AboutUI(VFXWindow):
    WindowID = PREFIX + 'AboutUI'
    WindowName = PREFIX + 'AboutUI'
    WindowDockable = True

    def __init__(self, parent=None, **kwargs):
        super(VFXWindow, self).__init__(parent, **kwargs)

        # add the window icon
        self.icon = QtGui.QIcon(area28.PATH + '/../../icons/logo.svg')
        self.setWindowIcon(self.icon)

        # build the interface for the window
        self.container = QtWidgets.QWidget()
        self.main_layout = QtWidgets.QVBoxLayout()
        self.container.setLayout(self.main_layout)
        self.setCentralWidget(self.container)

        # initialize the interface
        self.init_ui()

    def init_ui(self):

        # add the banner
        self.banner = QtSvg.QSvgWidget(area28.PATH + '/../../icons/banner.svg')
        self.banner.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)

        # add our widgets to the layout
        self.main_layout.addWidget(self.banner)
```

**Comment by huntfx** [comment]
Hey,
It's great you're trying to _properly_ make use of this, I think you're the first outside of where I work haha.

Your first few questions are related to parenting which is what it should be doing, however you are completely bypassing `MayaWindow.__init__` and `VFXWindow.__init__`. Try change `super(VFXWindow, self)` to `super(AboutUI, self)`, hopefully it should fix your issue.

> What would be the best way to approach multiple windows?

`VFXWindow` keeps track of all that. Generally, you don't need any `create` function, you just call `AboutUI.show()` and it will close down the previous instance before loading the new one. It works off `WindowID`, so as long as you give your different windows a unique ID, then it should be able to cope with them all.

This is pretty much how I intended the code to be run:
```python
from somewhere import MyTool
MyTool.show()
```

> Is there somewhere I can find a slightly more complete example

Since `VFXWindow` wraps over `QMainWindow`, there is very little that I can think to demonstrate which wasn't done in the simple examples. The more complex an example, the more regular PySide code there will be, and it'd be harder to see the specific things this class can do. If there's something in particular you think would be useful though let me know, documentation is not my strong point haha.
There's a couple of extra windows in the [tests](https://github.com/Peter92/vfxwindow/tree/master/tests) folder just making sure certain features are working.

**Comment by garysb** [comment]
Thanks Peter,

Switching the super call solved the issue. not sure how that got in there.
